#!/bin/bash --->shebang chars
every shell script file ends with .sh "files.sh"
# --This is a comment
chmod 755 first.sh or chmod +x filename.sh -->To make files executable.

passing variables:
MY_MESSAGE(variable)="Hello World"(string)
echo $MY_MESSAGE
